name: Auto-merge dependabot updates
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  test:
    name: Auto-merge dependabot updates
    runs-on: ubuntu-latest
    steps:
      - uses: akheron/dependabot-cron-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}